// D2C Artificial & Imitation Jewellery Catalog for Golden Heera
const PRODUCTS_DATA = [
    {
        id: 1,
        name: "American Diamond Stud Earrings",
        price: 399,
        originalPrice: 799,
        category: "earrings",
        collection: "ad",
        image: "https://lh3.googleusercontent.com/aida-public/AB6AXuBpt1V-5wXNXXtugP9Embqk2zSX_1aNmdK9Dex0ZURGgOKrhaxoy0Jf-l5AhMYUZlVKA6LlpFmvA8wxcmi2yeHy7to6UWQkfo7mldhk-IxUFIYC273jXyw2yjo5fezo_YyAR2rJqUJ-cY58k-awjaSWEQ2qbiMbfIvxFIf4QEGJeFT889if5tpNmoV_P1TDdeQp_WwE1nlP39W9MKvMRYyX9divHj6OsEjfatdsFsj-LU_8x9EpmSUxJw",
        hoverImage: "https://lh3.googleusercontent.com/aida-public/AB6AXuChflheDeviyQ6zXYQ9X8MXGsoJ9i4e32gWN6wMsfCinLit6z55zPJ_MjzKNdTxy2MFc-TwJfOqQojE4pyZcdUQU9YvIB4HMV60ECwhY52COFugm5KYM6CQau8QNgXAJ7GXT-NAW0YxD8cXNShNvfWx_Xl0AE38c230uS9S7eXiIZJFGOPGQry890gA3hKRQP_xYCGt-h4l0XG18Le3t3QTcRThpo-u3rIJ3sw9XE_AmEfnkRsI4zWl6A",
        rating: 4.8,
        reviewsCount: 342,
        isNew: true,
        isBestseller: true,
        isTrending: false,
        isLimited: false,
        material: "AAA Cubic Zirconia, Rhodium Silver Polish",
        description: "Elegant daily wear stud earrings handcrafted with shimmering American Diamonds. Perfect for office wear or casual outings.",
        details: ["Anti-tarnish coating", "Skin friendly alloy", "Push-back closure", "6 months warranty"]
    },
    {
        id: 2,
        name: "Kundan Chandbali Earrings",
        price: 899,
        originalPrice: 1799,
        category: "earrings",
        collection: "kundan",
        image: "https://lh3.googleusercontent.com/aida-public/AB6AXuBKADJtdQiqERuDX7Cne7wWvVHYuHi46nuZ2G1JDjsk3Z7Zs4qkrNcmRAqzAJ6ElJijjAtupUQBKzantfq2IpPr7bl9HmkqmYEuYLAIY3HsnIJd3DCq0JAOextZTxnT8_GMX9k5tEvY12e49ocsKmprN4tX7zBrYMq7lEZjxMaaeNgztLlESq7xsY0AfU6ATFVOZAPyuHcUd72U7-TrEZV2r-fSlsXV10un3q2YjL_zl3_6GfS0Ebie4w",
        hoverImage: "https://lh3.googleusercontent.com/aida-public/AB6AXuCbpa1GWiusXmGsbFjJWQXQ44NDOj8z0kXHmIjtinkQOHI1L8_XOkSIxGmE77--wSelFp83KwH5ciiJZ7y3N2zzBS1mJi6BMakCl0KMfgoR5wmyA8RDjYif0Y9mk4o_kWD50SkRImd6mFZr-i9gHBTvfcHD9_qe2liqg0fIpFTJDoNtLQEfaAulo9eMyb5U7Re5mUk-BYS5cXDjJvNDBA-9TB1EilRP4KIa0iwXMpP78mXxrWNOyt50Nw",
        rating: 4.7,
        reviewsCount: 189,
        isNew: false,
        isBestseller: true,
        isTrending: true,
        isLimited: false,
        material: "Kundan Stones, Faux Pearls, 22K Gold Plating",
        description: "Exquisite traditional Chandbali earrings set with uncut Kundan and bordered with pearls. A festive favorite.",
        details: ["Handcrafted in Jaipur", "Lead & Nickel free", "Perfect for weddings & festivals", "Store in dry pouch"]
    },
    {
        id: 3,
        name: "Temple Jhumka Earrings",
        price: 699,
        originalPrice: 1399,
        category: "earrings",
        collection: "temple",
        image: "https://lh3.googleusercontent.com/aida-public/AB6AXuBBWRBlD1OBS_IpfWC-0ZkH3GL62Gvmbojt2x3qZOOzYZhjtCvliN9qil4WE7kxxs2W86lUkHyNmE4dmqSsN3ZEoBrreIShKoq-POE5wRi0QcGrSvC3MEdA9ytvk0kLZmol3uZPbGtIvFlWhdtRXvuMDyo06W7QiP2sC5NfGuYMHw3N5uOfJUtbEleYlXwvCXJ2CP4mHcgD9itstIMxGfIJnJBKOBuv1dYXDarNXeH2_IC-GyGW_4OfEw",
        hoverImage: "https://lh3.googleusercontent.com/aida-public/AB6AXuCuN2GVNow9ZK_YbHTw_pvHJ5N57V8eu3wu-BY0ox3gCnQiCVRa-3f16owcsm8__97McbeAT7Hf41f3ycqRoOyyOy3xmnEpszqwaVeHu7QPxsepcaEJaqBZmvRE2YZoW-I0DJkDWxNbpNEJVNTMWJTKCZ8AfqZuuRXQx5RFp_dBxD2DwboFHsTHtNgCAei8bhmAYbHuFc5UBZu4zbtFM-iJ9MpyzJCjoBYr9l5ESJcEUMWypHkWdaJk9A",
        rating: 4.6,
        reviewsCount: 120,
        isNew: true,
        isBestseller: false,
        isTrending: false,
        isLimited: false,
        material: "Brass Base, Antique Gold Finish, Red Kemp Stones",
        description: "Classic South Indian Kemp Temple jhumkas with Goddess motifs. Traditional aesthetics for traditional occasions.",
        details: ["Gold matte finish", "Delicate hand carvings", "Lightweight design", "Ideal for silk sarees"]
    },
    {
        id: 4,
        name: "Bridal Kundan Necklace Set",
        price: 3499,
        originalPrice: 6999,
        category: "necklaces",
        collection: "bridal",
        image: "https://lh3.googleusercontent.com/aida-public/AB6AXuDjlD7HIvSM8CTLilPKzCm3OTql9hDjX_GFiyFlnt5OWRDIw446CCiksXMim4vVKxMCkW9PkDZfdGTYuLn-BI1GqJ8SGpnuWyVVgIpIhDq3-qowJ5MaBeQQqQ5rOMwSRJEFw1eUnPZu0a3HGxFe2H4owRg5-toVbouKCnUwzjymItgJ4PnXWQEHhSs1njO0TLbfIcyfZDYXRJiE5KZ9V2CtBfE7AfZYMIsLOEk5GT-Zj934CXsT6I3yZQ",
        hoverImage: "https://lh3.googleusercontent.com/aida-public/AB6AXuCZg48N-oHGT_gF1UT4teb-Shhjdo3bc41o-eBLg6yeQAY9mys4TfZjWS0Fa6DwX3WTdTWRBmIXaaKVOg-MGdlRsjp6tMpPMIaTUQ5AfiSOZYVKcIZxYlR15Ti9FsMbCD2cOEYWBir4bc2eZG6y4ySjoHRZJugkTY4F3snut9c_6YOjBAxFjAluWwkdhG46CeGCa8gIygGBQlQbTTWLH6-2hl4mJM_VgqqX9bdbPEm64FiKE4sSc5YEuQ",
        rating: 4.9,
        reviewsCount: 412,
        isNew: false,
        isBestseller: true,
        isTrending: true,
        isLimited: true,
        material: "Grade A Kundan Glass, Semi-Precious Emeralds, 22K Gold Plated",
        description: "Stunning bridal choker and drop necklace set, complete with matching earrings. Heavily detailed antique polish work.",
        details: ["Includes Choker & Long Necklace Set", "Earrings & Maang Tikka included", "Adjustable dori back tie", "Luxury red velvet box packing"]
    },
    {
        id: 5,
        name: "Temple Lakshmi Necklace Set",
        price: 2499,
        originalPrice: 4999,
        category: "necklaces",
        collection: "temple",
        image: "https://lh3.googleusercontent.com/aida-public/AB6AXuBnLdTCTvttsD3cRSlNb1Oygz19YGYniUWMJJYQ6v7_7KBsJgq8NXV4w-zmQ5-Tr1MslqqoTHNLA2dTGqr_RytR1hOZ4pwhLHliJ0OL1jDdZEMysUZeTwU5gS3O0DG_mH7UNjAKxvyMmNxkH41xKAfgCzqVdQ_cF1G6wn0joUka87IZTZYXqjAsLi_1LrurfzRNx3t9dGIPSUzcBmx-OKnl3kAQ4ZG5EXeUrXg1Jt_Uo0cSYrYMDjqQSQ",
        hoverImage: "https://lh3.googleusercontent.com/aida-public/AB6AXuDVq7JarC1mMsqA7iGxhNQbc4SP3L2y5fUpcts0g4yOUrHLBQOhyLSDjCnzCdzCRI5JNo-F4O_ajOMljhUhE5nocgm7kFunG7Fn5PnjrV8OszBD6xA5CfOlDADud32U2lZT2prnGZ2d36pyzJEwQ5wXWD3WKpqRNaN40IP5LBBGxdc_uTB81o_xZGxnh0XdFeqbt2aLiK_XB_1Uq4Ni_p9EGZUhs15g-HbP83BcdlN0BEHGoQ87vXMXNw",
        rating: 4.8,
        reviewsCount: 220,
        isNew: false,
        isBestseller: true,
        isTrending: false,
        isLimited: false,
        material: "Copper Base, Matte Gold Finish, Ruby Kemps",
        description: "Elegant long haram temple necklace showcasing detailed Goddess Lakshmi carvings. Accented with ruby pink stones.",
        details: ["Matte gold finish", "Heavy heritage look", "Comes with matching earrings", "Sweat resistant coating"]
    },
    {
        id: 6,
        name: "American Diamond Choker Set",
        price: 1899,
        originalPrice: 3799,
        category: "necklaces",
        collection: "ad",
        image: "https://lh3.googleusercontent.com/aida-public/AB6AXuD3tElvkQRVMTdajCQZ38Zhn19w5d9uxPfpGaT791cBV2Ifx0bgdPqoDM9z-Bp_jO0t12Cbc2rCq5u99Z67Fmlpiyw_KAlKZRNgwDeT65are75H7WFPsDJvAlr3Mg2U-NrJG0gp8YxyvgZeIk97kiHceH_yws8I-_8udUBJiuOULa_NJ0J5aGQ_sftW0yIXTEZ5Q-pEMsdr4KyOtOl2fjPJFG6XFOC8hPedI5aioFwYUV_mxAWa-jIjDw",
        hoverImage: "https://lh3.googleusercontent.com/aida-public/AB6AXuBycTOvNM8tQdsw2ITc-XkFKWnZRfiqz2HCaa4dWN5QyHJdks7FzKsjbeRChkWzh1TI7IvhRobnqYXo4Xd74hvxfcbKrCmx3TZbozZ2jU32b7I0kGU-7MPSOn_tEPnESTOzEWPZIRegIWewJp99w3GbNncpXyPoqUnbz-z_ThnjuILZxclyqxMsTYwDWqYn748IN3bHgF4E7uuZrH9HWh97NnLLPwT1mZMbv-tIoKuvZsrav8IyGTJTAw",
        rating: 4.9,
        reviewsCount: 153,
        isNew: true,
        isBestseller: false,
        isTrending: true,
        isLimited: false,
        material: "Zirconia crystals, Silver Rhodium Polish",
        description: "An elegant, modern choker featuring brilliant-cut American Diamonds. Ideal for cocktails, parties, and bridesmaid wear.",
        details: ["Premium Rhodium finish", "Sparkles like real diamonds", "Adjustable link chain", "Includes drops studs"]
    },
    {
        id: 7,
        name: "Temple Kemp Bangles Set",
        price: 999,
        originalPrice: 1999,
        category: "bangles",
        collection: "temple",
        image: "https://lh3.googleusercontent.com/aida-public/AB6AXuCiXQgqJeMBw-vCDq3O1M-ix-rVeYlkN2pzSItppjGgpaZx6unZF6ZhChSLX8DfbUXyZHZIuJwAsvGckIcJOXshuxVcJgaJQ2rDBbGeFaPkySPpf-W1gxXlNWm0IbJsZH5VKvQHW9tvsWTbBk6Ux5nYs0C1qFx7SHU2KejJPNmp6V83Jjx-9Nkvz80v0tcmVnw54ZU5M3gOOnfDx4BIajqO3YtGDg7ssVe4j9NlB3nxeavuJQVEjU1wpw",
        hoverImage: "https://lh3.googleusercontent.com/aida-public/AB6AXuCnT6j4g-8x2qIvmGZZckMtwyY5rwfMAjXd-YRQeSZby9nOoIrjuvujNbjeo7mImBnyLtvBLjYG-W3SAqm2q_q75faLtBZGN4iD32H_4WY7phe_3m4aThJ7bsXC4zLtX-43DMuB_72hwc4wjskJlw3figVSoS39BR5m9rSmT5OzqRkirNp6Gbj3nG-KEQYOI5ui3gVwoKlBmb-CpU8JVWX-EfovniPvZJdumDhbdeuU-6XZGB1ym5PxtA",
        rating: 4.6,
        reviewsCount: 98,
        isNew: false,
        isBestseller: true,
        isTrending: false,
        isLimited: false,
        material: "Brass, Kemp stones, Matte Gold Coating",
        description: "Set of 4 traditional kemp bangles with intricate carvings. Elegant statement wear for wedding ensembles.",
        details: ["Set of 4 bangles", "Available sizes: 2.4, 2.6, 2.8", "Durable matte polish", "Avoid direct contact with water"]
    },
    {
        id: 8,
        name: "Adjustable Stone Ring",
        price: 249,
        originalPrice: 499,
        category: "rings",
        collection: "daily",
        image: "https://lh3.googleusercontent.com/aida-public/AB6AXuBX1S7okuzyBArf0olVWM1ctL0WxI5amwQwAEtjw6bVcNqxIr3uEtmy2A5qY6d9WrUDeNPUVBPw4Dg8MI7uusHA3Fu5rEPesb9pSY3cY7LyPYNKdv0--QkXgpDsnbdwb1upUScSaUOdomaLwe4ogR5eVkaxKg7iSxh65jSzju2q8TYkue181sYiup3FawqTgBdpo-mrZBBzjfJtn5rbB2lXdON9ovBY968W_WO4qikfT9bGeP06J3wnJg",
        hoverImage: "https://lh3.googleusercontent.com/aida-public/AB6AXuBghCZSNk1KpGSxO1jdz3dtWfIN3leBtLu8Gy17Yb7FseKZ2sJK_9Fnl3PepcdJPyZ1bNkKPrMICyBP8kGzhPHUA4Kuoxlowkm0SXxR3RmQv6GQ-8ywypNI7g-X74uiaaHGL-BYeTSsVbcCr0BvirydylHH8G4-2iAE2Yc-_Kpt2PfG7ymxHkh1JHgyEF_OwsdK1c-4s2d1piHE7x_HfDriQhsKjGA39lztBRgIhOd8IeVy4AUW2TMylw",
        rating: 4.5,
        reviewsCount: 215,
        isNew: false,
        isBestseller: true,
        isTrending: true,
        isLimited: false,
        material: "Alloy, Cubic Zirconia, Emerald Green Stone",
        description: "Classic D2C style adjustable ring featuring a large faceted emerald green synthetic stone surrounded by CZ crystals.",
        details: ["One size fits all (adjustable)", "Comfortable daily wear", "Elegant solitaire look", "Excellent gifting item"]
    },
    {
        id: 9,
        name: "American Diamond Bracelet",
        price: 899,
        originalPrice: 1799,
        category: "bracelets",
        collection: "ad",
        image: "https://lh3.googleusercontent.com/aida-public/AB6AXuBytmX6cZ1gkwoKE-dOVrAU8PWXVL49ajMyvGNQm0Bs3Hnr0QG1SD2qX3AP1qQ2ei-X7TWgF3P9rbx_SUyZiURVjviqGtTYaoSNbdAkV2hUbcDnd6Zw_Q-ZBRBc6AQLiFJIR1eZCecbDtHCtSpcVEDt1mX8P5ZuHSnlD2bJS3BLrqhjQFm_SxDKvjqeljwiJkiqW6wh9VYR8WDF4hEf77WVBJG2ZWrqlwl7Y8sucAB_5ZhOm_kaQr5Ssw",
        hoverImage: "https://lh3.googleusercontent.com/aida-public/AB6AXuBycTOvNM8tQdsw2ITc-XkFKWnZRfiqz2HCaa4dWN5QyHJdks7FzKsjbeRChkWzh1TI7IvhRobnqYXo4Xd74hvxfcbKrCmx3TZbozZ2jU32b7I0kGU-7MPSOn_tEPnESTOzEWPZIRegIWewJp99w3GbNncpXyPoqUnbz-z_ThnjuILZxclyqxMsTYwDWqYn748IN3bHgF4E7uuZrH9HWh97NnLLPwT1mZMbv-tIoKuvZsrav8IyGTJTAw",
        rating: 4.8,
        reviewsCount: 165,
        isNew: true,
        isBestseller: true,
        isTrending: false,
        isLimited: false,
        material: "Rhodium Polish, AAA CZ Crystals",
        description: "Dainty tennis bracelet accented with round-cut American Diamonds. Fits all wrist sizes with adjustable hook lock.",
        details: ["Anti-tarnish silver plating", "Flexible mesh links", "Elegant hook closure", "Includes certificate card"]
    },
    {
        id: 10,
        name: "Temple Kada Bangle",
        price: 599,
        originalPrice: 1199,
        category: "bangles",
        collection: "temple",
        image: "https://lh3.googleusercontent.com/aida-public/AB6AXuBEvCBEZT3sKzvYUZrktD9eB1aD-cvmYisseE4v9ror_bNWTHyWiRWshupdw9Q3D5s1tEAdgliDYNy08j9wt3sOUaQYZ5GStYjbsIsDI9PDQ-o1OF5rtd84QWn7GNp4jw2D7Cze_yo2Rn-LQSVqSPTP2nsAQ_y8dddVyXtu7kpM3V8uRDdCdIjXswHpIE4hEDDZMh9Ige-hGFTBTIeI4n7YvYpsnypVIH3zzBbcM-7O8f3IRPsKeAGMrQ",
        hoverImage: "https://lh3.googleusercontent.com/aida-public/AB6AXuCiXQgqJeMBw-vCDq3O1M-ix-rVeYlkN2pzSItppjGgpaZx6unZF6ZhChSLX8DfbUXyZHZIuJwAsvGckIcJOXshuxVcJgaJQ2rDBbGeFaPkySPpf-W1gxXlNWm0IbJsZH5VKvQHW9tvsWTbBk6Ux5nYs0C1qFx7SHU2KejJPNmp6V83Jjx-9Nkvz80v0tcmVnw54ZU5M3gOOnfDx4BIajqO3YtGDg7ssVe4j9NlB3nxeavuJQVEjU1wpw",
        rating: 4.7,
        reviewsCount: 74,
        isNew: false,
        isBestseller: false,
        isTrending: true,
        isLimited: false,
        material: "Copper Base, Gold Matte Finish",
        description: "A single openable Kada bangle, richly engraved with divine temple motifs. An absolute heritage style.",
        details: ["Openable clasp (screw lock)", "Single kada unit", "High-detail gold embossing", "Sturdy structure"]
    },
    {
        id: 11,
        name: "Oxidised Silver Choker Set",
        price: 599,
        originalPrice: 1199,
        category: "necklaces",
        collection: "oxidised",
        image: "https://lh3.googleusercontent.com/aida-public/AB6AXuAhuKO7ceUIQlczRrGLyWRrGcA3k5RZEgNJ_g6OU9YxAf0AfqFTbK04vrfpKCwPSf_9pADiHfHnN1-cbpde4bC4ZxerPPrHzQkDF54FBYNZfTZeANmKeUEByqNNa_8_5eE7jBQ9ppVM5y_x5XrZYdiF2LPtuEEqFmW8m-GDMrWynR36gSDS00SrAdrkOIhtSlc2XRo3kCk64ibARPWqIL480qtbehgHxj7s-j76j3FIm2dzIDBwOpfIzA",
        hoverImage: "https://lh3.googleusercontent.com/aida-public/AB6AXuDn5h294hP-3ZkabK712wBgNCsG9Ko7c1b4BNXBM3yI_YD7NkjxwSxfo7yBBeVBA9g_Ru_KBquBe4EW22msMjjoWnr3nCdifXsvsutZMBeiLV7l47dG0OrTP8y0RBmsPgJm7IeCD52_Agn28fne_ZyIwp4BIS9WnzZvkcqd2wIfh4vniLbG2Xrd1QdNa_iGxrMnyXRnIBdoglWG3Qc4mUH0P9_nQzwyhUlPets8f6q70lF2IMRnwLJ7Cg",
        rating: 4.7,
        reviewsCount: 295,
        isNew: true,
        isBestseller: true,
        isTrending: true,
        isLimited: false,
        material: "German Silver base, Oxidised Finish, Black Thread Tie",
        description: "Trendy boho style oxidised silver choker set with hanging ghungroos. Fits beautifully on fusion wear.",
        details: ["Choker + matching drop studs", "Adjustable black cord back", "Classic tribal carvings", "Skin-friendly plating"]
    },
    {
        id: 12,
        name: "Pearl Drop Daily Earrings",
        price: 299,
        originalPrice: 599,
        category: "earrings",
        collection: "daily",
        image: "https://lh3.googleusercontent.com/aida-public/AB6AXuDOeka2yoUhoJfSxCQk4nbiow_eZcUJfwz1368N2m5HD3kkCvYKhujGPkZz-DLx2YlBuyC45ou9QW8coWA7Hfmnp4k0LOwdiaqRs9mqrvftgQFHhLeL5Z_Y3Ys1c8OJ52uvcRC2fTTzyDxg1nV-gS21O9IgEHJ-rYLH73CYwo0yFTBq6WyoPoXYgzLx4EXhZ38wD0PsNa_pDYCvpPECVKX3p2n64HJaBvV1v2YGEGr6P5gsQUK9sEMmtw",
        hoverImage: "https://lh3.googleusercontent.com/aida-public/AB6AXuBKADJtdQiqERuDX7Cne7wWvVHYuHi46nuZ2G1JDjsk3Z7Zs4qkrNcmRAqzAJ6ElJijjAtupUQBKzantfq2IpPr7bl9HmkqmYEuYLAIY3HsnIJd3DCq0JAOextZTxnT8_GMX9k5tEvY12e49ocsKmprN4tX7zBrYMq7lEZjxMaaeNgztLlESq7xsY0AfU6ATFVOZAPyuHcUd72U7-TrEZV2r-fSlsXV10un3q2YjL_zl3_6GfS0Ebie4w",
        rating: 4.6,
        reviewsCount: 162,
        isNew: false,
        isBestseller: true,
        isTrending: false,
        isLimited: false,
        material: "Faux South Sea Pearls, Brass Gold Polish",
        description: "Minimalist floral studs with drop pearls. Elegant accessory for corporate shirts or simple kurtis.",
        details: ["Perfect lightweight fit", "Comfort hook wear", "High luster pearls", "Durable gold color coating"]
    },
    {
        id: 13,
        name: "Antique Gold Kada",
        price: 1499,
        originalPrice: 2999,
        category: "bangles",
        collection: "temple",
        image: "https://lh3.googleusercontent.com/aida-public/AB6AXuCiXQgqJeMBw-vCDq3O1M-ix-rVeYlkN2pzSItppjGgpaZx6unZF6ZhChSLX8DfbUXyZHZIuJwAsvGckIcJOXshuxVcJgaJQ2rDBbGeFaPkySPpf-W1gxXlNWm0IbJsZH5VKvQHW9tvsWTbBk6Ux5nYs0C1qFx7SHU2KejJPNmp6V83Jjx-9Nkvz80v0tcmVnw54ZU5M3gOOnfDx4BIajqO3YtGDg7ssVe4j9NlB3nxeavuJQVEjU1wpw",
        hoverImage: "https://lh3.googleusercontent.com/aida-public/AB6AXuCnT6j4g-8x2qIvmGZZckMtwyY5rwfMAjXd-YRQeSZby9nOoIrjuvujNbjeo7mImBnyLtvBLjYG-W3SAqm2q_q75faLtBZGN4iD32H_4WY7phe_3m4aThJ7bsXC4zLtX-43DMuB_72hwc4wjskJlw3figVSoS39BR5m9rSmT5OzqRkirNp6Gbj3nG-KEQYOI5ui3gVwoKlBmb-CpU8JVWX-EfovniPvZJdumDhbdeuU-6XZGB1ym5PxtA",
        rating: 4.7,
        reviewsCount: 88,
        isNew: true,
        isBestseller: false,
        isTrending: true,
        isLimited: false,
        material: "Copper Base, Antique Gold Matte Polish",
        description: "Sophisticated ethnic kada bangle with detailed micro-engravings. Fits beautifully for family celebrations.",
        details: ["Sturdy copper base", "Micro-plated gold finish", "Smooth borders inside", "Safe for sensitive skin"]
    },
    {
        id: 14,
        name: "Floral Party Wear Earrings",
        price: 499,
        originalPrice: 999,
        category: "earrings",
        collection: "party",
        image: "https://lh3.googleusercontent.com/aida-public/AB6AXuChflheDeviyQ6zXYQ9X8MXGsoJ9i4e32gWN6wMsfCinLit6z55zPJ_MjzKNdTxy2MFc-TwJfOqQojE4pyZcdUQU9YvIB4HMV60ECwhY52COFugm5KYM6CQau8QNgXAJ7GXT-NAW0YxD8cXNShNvfWx_Xl0AE38c230uS9S7eXiIZJFGOPGQry890gA3hKRQP_xYCGt-h4l0XG18Le3t3QTcRThpo-u3rIJ3sw9XE_AmEfnkRsI4zWl6A",
        hoverImage: "https://lh3.googleusercontent.com/aida-public/AB6AXuBKADJtdQiqERuDX7Cne7wWvVHYuHi46nuZ2G1JDjsk3Z7Zs4qkrNcmRAqzAJ6ElJijjAtupUQBKzantfq2IpPr7bl9HmkqmYEuYLAIY3HsnIJd3DCq0JAOextZTxnT8_GMX9k5tEvY12e49ocsKmprN4tX7zBrYMq7lEZjxMaaeNgztLlESq7xsY0AfU6ATFVOZAPyuHcUd72U7-TrEZV2r-fSlsXV10un3q2YjL_zl3_6GfS0Ebie4w",
        rating: 4.5,
        reviewsCount: 76,
        isNew: false,
        isBestseller: false,
        isTrending: true,
        isLimited: false,
        material: "Zinc Alloy, CZ Crystals, Rose Gold Polish",
        description: "Intricately designed floral studs with dangling drop crystals. Highly sparkling cocktail wear.",
        details: ["Lightweight alloy", "AAA-Grade Zirconia", "Rose gold micro plating", "Ziploc storage safe"]
    },
    {
        id: 15,
        name: "Layered Party Necklace",
        price: 1299,
        originalPrice: 2599,
        category: "necklaces",
        collection: "party",
        image: "https://lh3.googleusercontent.com/aida-public/AB6AXuBFsCZi2EIeCkEAW1myc-uI464NEVsrqkl5y-7xmg8LSBa2rdWbp8e4eP9qKi9ZT3f3oiIvC-R_4r6_LIIKIjXVQ0Ntvmqmv8G-FJdTg8dmy4kfDJEWdYvdaQL9Zc48aNhpTG0ayYhYA1vj19IZVhhPhUQWra_YRH3TbjiCEQhLoTM2gyWQnjHN6xHBCpo4tHsqZ3R7XDZ7kyYjU8_MFdeIk5E20gVXjLZ9LnskJMmFiN80DV4RfsIo0A",
        hoverImage: "https://lh3.googleusercontent.com/aida-public/AB6AXuCv5iRzKY0qyByko37tI0lv3Km8d3IX8GdPGjKfQ4OnK22FsrElqKYVZZg5xlyOQaD0KH_Y3J6TfprkZ_NO7nRlF8IPl0Yvm-NS91-D2ey-97rw2QM7YrhojDmwSyak0sVmsnxu7YUhCdBSevmJljGsFTK2pfi3kCror6uIOJqC1IrwpQrWTInk6YeBxqIp8P7H5T_wmpRHDmvKe5FQygTtOOozqpM06RTznXJAhb4QPbWpnPM-i1NvEA",
        rating: 4.7,
        reviewsCount: 112,
        isNew: true,
        isBestseller: false,
        isTrending: false,
        isLimited: false,
        material: "Alloy Base, Rhodium Finish, Sapphire Blue CZ",
        description: "Dazzling layered necklace adorned with deep sapphire blue synthetic stones and brilliant AD border lines.",
        details: ["Includes matching studs", "Dual-layered design", "Smooth lobster clasp closure", "Keep away from moisture"]
    },
    {
        id: 16,
        name: "American Diamond Ring",
        price: 349,
        originalPrice: 699,
        category: "rings",
        collection: "ad",
        image: "https://lh3.googleusercontent.com/aida-public/AB6AXuBX1S7okuzyBArf0olVWM1ctL0WxI5amwQwAEtjw6bVcNqxIr3uEtmy2A5qY6d9WrUDeNPUVBPw4Dg8MI7uusHA3Fu5rEPesb9pSY3cY7LyPYNKdv0--QkXgpDsnbdwb1upUScSaUOdomaLwe4ogR5eVkaxKg7iSxh65jSzju2q8TYkue181sYiup3FawqTgBdpo-mrZBBzjfJtn5rbB2lXdON9ovBY968W_WO4qikfT9bGeP06J3wnJg",
        hoverImage: "https://lh3.googleusercontent.com/aida-public/AB6AXuBxFObu3E-g-KBzvVVy6EnT0qz6XIRFQjTwya3BK2m0Ewt1fsdlgYXoRAWUh0Z4_kya8nC2pSEckhDUf4T8D0P_OrPyab210HD2HNiHY4EybTXViTVayh0di_9mqb9qrGgu5g6OKCaOsWrq255z2HHFGMieZgmhpYzq4fdadALuAsCOg65zN6T_6GSEpHkdwJYn0pkh2mkYwmUmodo8o0hQciJlPAUB2ch1Q8ghfKhQvJpVV7Ag6qmTJg",
        rating: 4.8,
        reviewsCount: 143,
        isNew: true,
        isBestseller: true,
        isTrending: false,
        isLimited: false,
        material: "Alloy, Cubic Zirconia crystals, Silver Polish",
        description: "Gleaming crown-cut American Diamond ring designed with adjustable band sizing. Perfect statement solitaire look.",
        details: ["Adjustable ring size", "Prong set stone", "Rhodium silver finish", "Comes in premium ring box"]
    }
];
